queue_rule:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=lint
      - check-success=test

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=v2
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success='lint'
      - check-success='test'
      - label!=do-not-merge
      - label=ready-to-merge
    actions:
      queue:
        method: merge
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})
