#
# This file originates from github.com/metal-toolbox/golangci-lint-config repo.
#

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  gofumpt:
    extra-rules: true
  govet:
    enable:
      - shadow
  lll:
    line-length: 140
  misspell:
    locale: US
  revive:
    confidence: 0

linters:
  enable-all: true
  disable-all: false
  # Linters we don't like
  # Comments help explain why its disabled or point at ones we should not disable but will take a little work
  # If its not commented its likely because its just too annoying or we don't find useful
  disable:
    - canonicalheader # some bmcs may care about header case (against http spec)
    - copyloopvar # requires go >=1.22
    - cyclop
    - depguard
    - err113 # todo(*maybe* enable in future PR)
    - errname # maybe should be enabled
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic # todo(enable in future PR)
    - godot
    - godox
    - gosec # todo(enable in future PR)
    - inamedparam
    - interfacebloat
    - intrange # requires go >=1.22
    - ireturn # should be enabled, ironlib needs some changes
    - lll # not previously enabled, ironlib and mctl both fail this
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns # should be enabled, probably
    - paralleltest
    - perfsprint
    - revive # todo(enable in future PR)
    - tagliatelle
    - tenv # should be enabled
    - testifylint # should be enabled
    - testpackage
    - thelper # should be enabled
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: ST(1003|1016)
    - path: bmc/(firmware|sel|user).go
      linters:
        - dupl
    - path: bmc/(firmware|power|reset)_test.go
      linters:
        - dupl
    - path: internal/redfishwrapper/client_test.go
      linters:
        - dupl
    - path: providers/supermicro/firmware_bios_test.go
      linters:
        - dupl
    - path: providers/supermicro/x11_firmware_bmc_test.go
      linters:
        - dupl
    - path: providers/supermicro/x11_firmware_(bios|bmc).go
      linters:
        - dupl
